img_dir_1 : #txt file that list your dataroot
img_dir_2 : 
img_dir_3 : 
img_dir_4 : 
img_dir_5 : 
img_dir_6 :
img_dir_7 :
img_dir_8 :
img_dir_9 :
img_dir_10 :
img_dir_11 :
img_dir_12 :
img_dir_13 :
img_dir_14 :
img_dir_15 :
img_dir_16 :
text_dir_1 :
text_dir_2 :
text_dir_3 : 
text_dir_4 : 
text_dir_5 :
text_dir_6 :
text_dir_7 :
text_dir_8 :
text_dir_9 :
text_dir_10 :
text_dir_11 :
text_dir_12 :
text_dir_13 :
text_dir_14 :
text_dir_15 :
text_dir_16 :
context_length : 88
