per_gpu_train_batch_size : 16 # 128 exeeds GPU memory
per_gpu_eval_batch_size : 1 # not used in CLIP training
n_gpu : 1
num_workers : 8
num_train_epochs : 300 # number of epochs to train

gradient_accumulation_steps : 1 # Number of updates steps to accumulate before backward

logging_steps : 1000 #  log every this steps
save_steps : 100000 # 1000 steps take 1 hour with 4 GTX1080 GPUs and batch size = 256 (64 per GPU)

saved_checkpoints : saved_checkpoints
logs : logs

optimizer:
  params:
    eps: 1.0e-08
    lr: 5e-4
    weight_decay: 0.1
  type: AdamW
